from typing import Dict, Literal

MetricKey = Literal[
    'person_days_generated',
    'total_expenditure',
    'avg_days_of_employment',
    'work_completion_rate',
    'total_households_completed_100_days',
    'female_participation_rate'
]

class TerminologyDef:
    def __init__(self, title_en: str, title_kn: str, description_en: str, description_kn: str, unit: str):
        self.title_en = title_en
        self.title_kn = title_kn
        self.description_en = description_en
        self.description_kn = description_kn
        self.unit = unit

    def to_dict(self, language: str = 'en') -> Dict[str, str]:
        if language == 'kn':
            return {
                'title': self.title_kn,
                'description': self.description_kn,
                'unit': self.unit
            }
        else:
            return {
                'title': self.title_en,
                'description': self.description_en,
                'unit': self.unit
            }

# Terminology definitions
terminology: Dict[MetricKey, TerminologyDef] = {
    'person_days_generated': TerminologyDef(
        title_en='Person-Days Generated',
        title_kn='ಮಾನವ-ದಿನಗಳು ಸೃಷ್ಟಿ',
        description_en='Total number of days of work provided to all individuals under the scheme, measured in lakhs.',
        description_kn='ಯೋಜನೆಯಡಿಯಲ್ಲಿ ಎಲ್ಲಾ ವ್ಯಕ್ತಿಗಳಿಗೆ ಒದಗಿಸಲಾದ ಒಟ್ಟು ಕೆಲಸದ ದಿನಗಳ ಸಂಖ್ಯೆ, ಲಕ್ಷಗಳಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ.',
        unit='lakhs'
    ),
    'total_expenditure': TerminologyDef(
        title_en='Total Expenditure',
        title_kn='ಒಟ್ಟು ವೆಚ್ಚ',
        description_en='Total amount of money spent on wages and materials for the scheme, measured in crores of rupees.',
        description_kn='ಯೋಜನೆಗೆ ಕೂಲಿ ಮತ್ತು ಸಾಮಗ್ರಿಗಳಿಗಾಗಿ ಖರ್ಚು ಮಾಡಿದ ಒಟ್ಟು ಹಣ, ಕೋಟಿ ರೂಪಾಯಿಗಳಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ.',
        unit='crores'
    ),
    'avg_days_of_employment': TerminologyDef(
        title_en='Average Days of Employment',
        title_kn='ಸರಾಸರಿ ಉದ್ಯೋಗದ ದಿನಗಳು',
        description_en='The average number of days of employment provided to each household.',
        description_kn='ಪ್ರತಿ ಕುಟುಂಬಕ್ಕೆ ಒದಗಿಸಲಾದ ಸರಾಸರಿ ಉದ್ಯೋಗದ ದಿನಗಳ ಸಂಖ್ಯೆ.',
        unit='days'
    ),
    'work_completion_rate': TerminologyDef(
        title_en='Work Completion Rate',
        title_kn='ಕೆಲಸ ಪೂರ್ಣಗೊಳಿಸುವಿಕೆ ದರ',
        description_en='The percentage of works started that have been completed.',
        description_kn='ಪ್ರಾರಂಭವಾದ ಕೆಲಸಗಳಲ್ಲಿ ಪೂರ್ಣಗೊಂಡಿರುವ ಶೇಕಡಾವಾರು.',
        unit='%'
    ),
    'total_households_completed_100_days': TerminologyDef(
        title_en='Households with 100 Days Work',
        title_kn='100 ದಿನಗಳ ಕೆಲಸ ಪೂರ್ಣಗೊಳಿಸಿದ ಕುಟುಂಬಗಳು',
        description_en='The number of households that have completed the full 100 days of guaranteed wage employment.',
        description_kn='ಪೂರ್ಣ 100 ದಿನಗಳ ಖಾತರಿಯ ಕೂಲಿ ಉದ್ಯೋಗವನ್ನು ಪೂರ್ಣಗೊಳಿಸಿದ ಕುಟುಂಬಗಳ ಸಂಖ್ಯೆ.',
        unit='households'
    ),
    'female_participation_rate': TerminologyDef(
        title_en='Female Participation Rate',
        title_kn='ಮಹಿಳಾ ಭಾಗವಹಿಸುವಿಕೆ ದರ',
        description_en='The percentage of total person-days generated by women.',
        description_kn='ಮಹಿಳೆಯರಿಂದ ಸೃಷ್ಟಿಯಾದ ಒಟ್ಟು ಮಾನವ-ದಿನಗಳ ಶೇಕಡಾವಾರು.',
        unit='%'
    ),
}

# Translations for UI elements
translations = {
    'en': {
        'selectDistrict': 'Select Your District',
        'district': 'District',
        'selectPlaceholder': 'Select a district',
        'locating': 'Detecting your location...',
        'autoDetected': 'Auto-detected',
        'summaryTitle': 'AI-Powered Insights',
        'summaryDescription': 'A simple summary of this month\'s performance.',
        'performanceSummary': 'Performance Summary',
        'improvementAreas': 'Areas for Improvement',
        'generate': 'Generate Insights',
        'generating': 'Generating...',
        'generateInsightsPrompt': 'Click the button to generate an AI-powered summary and suggestions.',
        'feedbackTitle': 'Was this information helpful?',
        'helpful': 'Yes',
        'notHelpful': 'No',
        'feedbackThanksTitle': 'Thank you!',
        'feedbackThanksDescription': 'Your feedback helps us improve.',
        'historicalTitle': 'Historical Performance',
        'historicalDescription': 'Compare performance over the last few months.',
        'historicalTrend': 'Trend over last few months',
    },
    'kn': {
        'selectDistrict': 'ನಿಮ್ಮ ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        'district': 'ಜಿಲ್ಲೆ',
        'selectPlaceholder': 'ಒಂದು ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        'locating': 'ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಪತ್ತೆಹಚ್ಚಲಾಗುತ್ತಿದೆ...',
        'autoDetected': 'ಸ್ವಯಂ-ಪತ್ತೆಹಚ್ಚಲಾಗಿದೆ',
        'summaryTitle': 'AI-ಚಾಲಿತ ಒಳನೋಟಗಳು',
        'summaryDescription': 'ಈ ತಿಂಗಳ ಕಾರ್ಯಕ್ಷಮತೆಯ ಒಂದು ಸರಳ ಸಾರಾಂಶ.',
        'performanceSummary': 'ಕಾರ್ಯಕ್ಷಮತೆ ಸಾರಾಂಶ',
        'improvementAreas': 'ಸುಧಾರಣೆಗೆ ಕ್ಷೇತ್ರಗಳು',
        'generate': 'ಒಳನೋಟಗಳನ್ನು ರಚಿಸಿ',
        'generating': 'ರಚಿಸಲಾಗುತ್ತಿದೆ...',
        'generateInsightsPrompt': 'AI-ಚಾಲಿತ ಸಾರಾಂಶ ಮತ್ತು ಸಲಹೆಗಳನ್ನು ರಚಿಸಲು ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.',
        'feedbackTitle': 'ಈ ಮಾಹಿತಿ ಸಹಾಯಕವಾಗಿದೆಯೇ?',
        'helpful': 'ಹೌದು',
        'notHelpful': 'ಇಲ್ಲ',
        'feedbackThanksTitle': 'ಧನ್ಯವಾದಗಳು!',
        'feedbackThanksDescription': 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ನಮಗೆ ಸುಧಾರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
        'historicalTitle': 'ಐತಿಹಾಸಿಕ ಕಾರ್ಯಕ್ಷಮತೆ',
        'historicalDescription': 'ಕಳೆದ ಕೆಲವು ತಿಂಗಳುಗಳಲ್ಲಿ ಕಾರ್ಯಕ್ಷಮತೆಯನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ.',
        'historicalTrend': 'ಕಳೆದ ಕೆಲವು ತಿಂಗಳುಗಳ ಪ್ರವೃತ್ತಿ',
    }
}
